# Tomcat Server
server:
  port: 8080

# Logger
logging.level:
  web: DEBUG
  '[com.example.ratemyprofs]': DEBUG
  '[org.hibernate.type]': INFO
  
# Active Profile
spring:
  profiles:
    active: prod
    
# Banner Text
#  banner:
#    charset: UTF-8
#    location: classpath:/banner/busyQA.txt
      
---

# Default Profile
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ratemyprofs?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC 
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-wait: 10000
      max-active: 15
      max-idle: 10
      initial-size: 3
      test-on-borrow: true
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: validate
        '[format_sql]': true
        use-new-id-generator-mappings: true
        dialect: org.hibernate.dialect.MySQLDialect
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  sql:
    init:
      continue-on-error: false
  config:
    activate:
      on-profile: default
      
      # Database Settings

---

# Prod Profile
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/ratemyprofs?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC 
    url: jdbc:mysql://ratemyprofs.cxmx2z21qzov.us-east-2.rds.amazonaws.com
    username: admin
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: validate
        '[format_sql]': true
        use-new-id-generator-mappings: true
        dialect: org.hibernate.dialect.MySQLDialect
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy 
  sql:
    init:
      continue-on-error: false
  config:
    activate:
      on-profile: prod
      
      # Database Settings
    