INSERT INTO PROF_COURSE(COURSE_ID_COURSE, PROF_ID_PROF) VALUES
	((SELECT ID_COURSE FROM COURSE WHERE COURSE_CODE='CSCC01'), (SELECT ID_PROF FROM PROF WHERE PROF_FIRST_NAME='Ilir'    AND PROF_LAST_NAME='Dema')),
	((SELECT ID_COURSE FROM COURSE WHERE COURSE_CODE='CSC301'), (SELECT ID_PROF FROM PROF WHERE PROF_FIRST_NAME='Ilir'    AND PROF_LAST_NAME='Dema')),
	((SELECT ID_COURSE FROM COURSE WHERE COURSE_CODE='PHLA10'), (SELECT ID_PROF FROM PROF WHERE PROF_FIRST_NAME='William' AND PROF_LAST_NAME='Seager'));