INSERT INTO PROF_DEPT(DEPT_ID_DEPT, PROF_ID_PROF) VALUES
	((SELECT ID_DEPT FROM DEPT WHERE DEPT_NAME='Computer and Mathematical Sciences'),      (SELECT ID_PROF FROM PROF WHERE PROF_FIRST_NAME='Ilir'    AND PROF_LAST_NAME='Dema')),
	((SELECT ID_DEPT FROM DEPT WHERE DEPT_NAME='Mathematical and Computational Sciences'), (SELECT ID_PROF FROM PROF WHERE PROF_FIRST_NAME='Ilir'    AND PROF_LAST_NAME='Dema')),
	((SELECT ID_DEPT FROM DEPT WHERE DEPT_NAME='Philosophy'),                              (SELECT ID_PROF FROM PROF WHERE PROF_FIRST_NAME='William' AND PROF_LAST_NAME='Seager'));